### ISSUE TITLE
support to pt_br local using gregorian calendar

### ISSUE THREAD

**Issue by guilherme-luccas** [shahabyazdi/date-object#8]
Hi @shahabyazdi, I created this PR to help me with pt_br locale  

https://github.com/shahabyazdi/date-object/pull/7

**Comment by shahabyazdi** [comment]
Hi
Thank you for your cooperation. I wrote a comment about one of the changes, I would appreciate it if you read it and tell me the result

**Comment by shahabyazdi** [comment]
The changes you made were published in the NPM registry,  `date-object` `v.2.1.2`, `react-date-object` `v2.1.6`
